# Generated by Django 6.0.6 on 2026-06-23 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('target_exam', models.CharField(max_length=100)),
                ('expected_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_stream', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('preferred_cities', models.CharField(max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('saved_colleges', models.PositiveIntegerField(default=0)),
                ('applications', models.PositiveIntegerField(default=0)),
                ('recommendations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
